"use strict";
var names = ["Василий","Пётр","Эльвира","Владимир","Аркадий","Даниил","Алёна","Антон","Степан" ,"Василиса"];
var jobs = ["Cлесарь", "Менеджер", "Премьер Министр", "Программист", "Президент", "Учитель"];
var ol=document.createElement("ol");
document.body.appendChild(ol);
for(var i = 0; i < 10; i++){
  var li = document.createElement("li");
  var divname = document.createElement("span");
  var divjob = document.createElement("span");
  var divage = document.createElement("span");
  var divsalary = document.createElement("span");
  li.appendChild(divname);
  li.appendChild(divjob);
  li.appendChild(divage);
  li.appendChild(divsalary);
  ol.appendChild(li);
  var name =  names[Math.floor(Math.random()*10)];
  var job = jobs[Math.floor(Math.random()*6)];
  var age = Math.floor(Math.random()*15+20);
  var salary =Math.floor(Math.random()*100+20);
  divname.innerHTML = "Имя : " + name + "<br>";
  divjob.innerHTML = "Профессия : " + job +"<br>";
  divage.innerHTML = "Возраст = " + age +"<br>";
  divsalary.innerHTML = "Зарплата = " + salary +"<br>";
  if (age <= 27 && age >= 20) divname.style.fontWeight = "bold";
  if (job === "Премьер Министр" || job === "Президент") li.style.textDecoration = "underline";
  if (name ==="Эльвира" || name ==="Алёна" || name ==="Василиса") li.style.fontSize = "150%";
  if (salary <= 50) li.style.background = "red";
  else if (salary <= 80) li.style.background = "yellow";
  else li.style.background = "green";
}
